name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - name: trigger Jenkins Job
      run : | 
        curl -X POST -k --user "jenkins:$USER_TOKEN" "http://192.168.56.1:8080/job/gi-light/buildWithParameters?token=forRemoteRun&Branch=${GITHUB_HEAD_REF}&cause=github_actions"
      env :
        USER_TOKEN : ${{ secrets.JENKINSUSER }}
