name: trigger jenkins job
on: [pull_resquest]
jobs:
  build:
   name: build
   runs-on: ubuntu-latest
   steps:
   - name: Jenkins_call
     uses: sameer1701/maven-hello@master
     with:
       url: "http://54.193.46.61:8080/"
       user: "jenkins"
       token: ${{ secrets.TOKEN }}
       job: "demo-git"

