name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
    - name: trigger Jenkins Job
      run : | 
        curl -X POST -k --user "jenkins:$USER_TOKEN" "http://54.193.46.61:8080/job/demo-git/build?token=forRemoteRun"
      env :
        USER_TOKEN : ${{ secrets.JENKINSUSER }}
