name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get Branch Name
      run: |
        echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
        echo "{ \"Branch\":\"${GITHUB_HEAD_REF}\" }" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Trigger jenkins job
      uses: toptal/jenkins-job-trigger-action@master
      with:
          jenkins_url: "http://54.176.222.225:8080"
          jenkins_user: "jenkins"
          jenkins_token: ${{ secrets.JENKINSOWN }}
          job_name: "demo-test"
          job_params: ${{ env.JSON_RESPONSE }}
          job_timeout: "3600" # Default 30 sec. (optional)
