name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - name: Branch Name
      run: echo ${GITHUB_HEAD_REF}
    - name: Trigger jenkins job
      uses: Gympass/jenkins-job-action@0.0.5
      with:
        jenkins_url: "http://54.219.122.189:8080"
        jenkins_user: "jenkins"
        jenkins_token: "${{ secrets.JENKINSOWN }}" # Consider declaring this as a Github secret, for security purposes.
        job_name: "demo-test"
        jenkins_params: '{"Branch": "${GITHUB_HEAD_REF}"}' # Optional.

